### This notebook is for the loading of all datasets used in this project along with an initial analysis

In [1]:
from datasets import load_dataset
import pandas as pd

In [2]:
def inspect_dataset(dataset, name):
    print("=" * 80)
    print(f"DATASET: {name}")
    print("=" * 80)

    print("\nAvailable Splits:")
    print(dataset)

    for split in dataset.keys():
        print(f"\n{'-'*60}")
        print(f"Split: {split}")
        print(f"Number of samples: {len(dataset[split])}")

        print("\nFeatures:")
        print(dataset[split].features)

        print("\nFirst Example:")
        print(dataset[split][0])

    print("\n")

## 1. MRPC

In [3]:
mrpc = load_dataset("glue", "mrpc")

inspect_dataset(mrpc, "MRPC")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

train-00000-of-00001.parquet:   0%|          | 0.00/649k [00:00<?, ?B/s]

C:\Users\bevan\anaconda3\envs\paraphrase\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\bevan\.cache\huggingface\hub\datasets--glue. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

validation-00000-of-00001.parquet:   0%|          | 0.00/75.7k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

test-00000-of-00001.parquet:   0%|          | 0.00/308k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3668 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/408 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1725 [00:00<?, ? examples/s]

================================================================================
DATASET: MRPC
================================================================================

Available Splits:
DatasetDict({
    train: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 408
    })
    test: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 1725
    })
})

------------------------------------------------------------
Split: train
Number of samples: 3668

Features:
{'sentence1': Value('string'), 'sentence2': Value('string'), 'label': ClassLabel(names=['not_equivalent', 'equivalent']), 'idx': Value('int32')}

First Example:
{'sentence1': 'Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .', 'sentence2': 'Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .', 'label': 1, 'idx': 0}

------------------------------------------------------------
Split: validation
Number of samples: 408

Features:
{'sentence1': Value('string'), 'sentence2': Value('string'), 'label': ClassLabel(names=['not_equivalent', 'equivalent']), 'idx': Value('int32')}

First Example:
{'sentence1': "He said the foodservice pie business doesn 't fit the company 's long-term growth strategy .", 'sentence2': '" The foodservice pie business does not fit our long-term growth strategy .', 'label': 1, 'idx': 9}

------------------------------------------------------------
Split: test
Number of samples: 1725

Features:
{'sentence1': Value('string'), 'sentence2': Value('string'), 'label': ClassLabel(names=['not_equivalent', 'equivalent']), 'idx': Value('int32')}

First Example:
{'sentence1': "PCCW 's chief operating officer , Mike Butcher , and Alex Arena , the chief financial officer , will report directly to Mr So .", 'sentence2': 'Current Chief Operating Officer Mike Butcher and Group Chief Financial Officer Alex Arena will report to So .', 'label': 1, 'idx': 0}

## 2. QQP

In [4]:
qqp = load_dataset("glue", "qqp")

inspect_dataset(qqp, "QQP")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

train-00000-of-00001.parquet:   0%|          | 0.00/33.6M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

validation-00000-of-00001.parquet:   0%|          | 0.00/3.73M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

test-00000-of-00001.parquet:   0%|          | 0.00/36.7M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/363846 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/40430 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/390965 [00:00<?, ? examples/s]

================================================================================
DATASET: QQP
================================================================================

Available Splits:
DatasetDict({
    train: Dataset({
        features: ['question1', 'question2', 'label', 'idx'],
        num_rows: 363846
    })
    validation: Dataset({
        features: ['question1', 'question2', 'label', 'idx'],
        num_rows: 40430
    })
    test: Dataset({
        features: ['question1', 'question2', 'label', 'idx'],
        num_rows: 390965
    })
})

------------------------------------------------------------
Split: train
Number of samples: 363846

Features:
{'question1': Value('string'), 'question2': Value('string'), 'label': ClassLabel(names=['not_duplicate', 'duplicate']), 'idx': Value('int32')}

First Example:
{'question1': 'How is the life of a math student? Could you describe your own experiences?', 'question2': 'Which level of prepration is enough for the exam jlpt5?', 'label': 0, 'idx': 0}

------------------------------------------------------------
Split: validation
Number of samples: 40430

Features:
{'question1': Value('string'), 'question2': Value('string'), 'label': ClassLabel(names=['not_duplicate', 'duplicate']), 'idx': Value('int32')}

First Example:
{'question1': 'Why are African-Americans so beautiful?', 'question2': 'Why are hispanics so beautiful?', 'label': 0, 'idx': 0}

------------------------------------------------------------
Split: test
Number of samples: 390965

Features:
{'question1': Value('string'), 'question2': Value('string'), 'label': ClassLabel(names=['not_duplicate', 'duplicate']), 'idx': Value('int32')}

First Example:
{'question1': 'Would the idea of Trump and Putin in bed together scare you, given the geopolitical implications?', 'question2': 'Do you think that if Donald Trump were elected President, he would be able to restore relations with Putin and Russia as he said he could, based on the rocky relationship Putin had with Obama and Bush?', 'label': -1, 'idx': 0}

## 3. PAWS

In [5]:
paws = load_dataset("paws", "labeled_final")

inspect_dataset(paws, "PAWS")

README.md: 0.00B [00:00, ?B/s]

C:\Users\bevan\anaconda3\envs\paraphrase\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\bevan\.cache\huggingface\hub\datasets--paws. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

train-00000-of-00001.parquet:   0%|          | 0.00/8.43M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

test-00000-of-00001.parquet:   0%|          | 0.00/1.24M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

validation-00000-of-00001.parquet:   0%|          | 0.00/1.23M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/49401 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/8000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/8000 [00:00<?, ? examples/s]

================================================================================
DATASET: PAWS
================================================================================

Available Splits:
DatasetDict({
    train: Dataset({
        features: ['id', 'sentence1', 'sentence2', 'label'],
        num_rows: 49401
    })
    test: Dataset({
        features: ['id', 'sentence1', 'sentence2', 'label'],
        num_rows: 8000
    })
    validation: Dataset({
        features: ['id', 'sentence1', 'sentence2', 'label'],
        num_rows: 8000
    })
})

------------------------------------------------------------
Split: train
Number of samples: 49401

Features:
{'id': Value('int32'), 'sentence1': Value('string'), 'sentence2': Value('string'), 'label': ClassLabel(names=['0', '1'])}

First Example:
{'id': 1, 'sentence1': 'In Paris , in October 1560 , he secretly met the English ambassador , Nicolas Throckmorton , asking him for a passport to return to England through Scotland .', 'sentence2': 'In October 1560 , he secretly met with the English ambassador , Nicolas Throckmorton , in Paris , and asked him for a passport to return to Scotland through England .', 'label': 0}

------------------------------------------------------------
Split: test
Number of samples: 8000

Features:
{'id': Value('int32'), 'sentence1': Value('string'), 'sentence2': Value('string'), 'label': ClassLabel(names=['0', '1'])}

First Example:
{'id': 1, 'sentence1': 'This was a series of nested angular standards , so that measurements in azimuth and elevation could be done directly in polar coordinates relative to the ecliptic .', 'sentence2': 'This was a series of nested polar scales , so that measurements in azimuth and elevation could be performed directly in angular coordinates relative to the ecliptic .', 'label': 0}

------------------------------------------------------------
Split: validation
Number of samples: 8000

Features:
{'id': Value('int32'), 'sentence1': Value('string'), 'sentence2': Value('string'), 'label': ClassLabel(names=['0', '1'])}

First Example:
{'id': 1, 'sentence1': 'Bradd Crellin represented BARLA Cumbria on a tour of Australia with 6 other players representing Britain , also on a tour of Australia .', 'sentence2': 'Bradd Crellin also represented BARLA Great Britain on a tour through Australia on a tour through Australia with 6 other players representing Cumbria .', 'label': 0}

## 4. MSCOCO Captions

In [6]:
mscoco = load_dataset("sentence-transformers/coco-captions")

inspect_dataset(mscoco, "MSCOCO Captions")

README.md: 0.00B [00:00, ?B/s]

C:\Users\bevan\anaconda3\envs\paraphrase\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\bevan\.cache\huggingface\hub\datasets--sentence-transformers--coco-captions. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

train-00000-of-00001.parquet:   0%|          | 0.00/23.9M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/414010 [00:00<?, ? examples/s]

================================================================================
DATASET: MSCOCO Captions
================================================================================

Available Splits:
DatasetDict({
    train: Dataset({
        features: ['caption1', 'caption2'],
        num_rows: 414010
    })
})

------------------------------------------------------------
Split: train
Number of samples: 414010

Features:
{'caption1': Value('string'), 'caption2': Value('string')}

First Example:
{'caption1': 'A clock that blends in with the wall hangs in a bathroom. ', 'caption2': 'A very clean and well decorated empty bathroom'}

## 5. ParaNMT

In [7]:
print("ParaNMT will be downloaded separately during the generation phase.")

ParaNMT will be downloaded separately during the generation phase.

## Overview

In [8]:
datasets = {
    "MRPC": mrpc,
    "QQP": qqp,
    "PAWS": paws,
    "MSCOCO": mscoco
}

for name, ds in datasets.items():
    print("=" * 50)
    print(name)

    for split in ds.keys():
        print(f"{split}: {len(ds[split])} samples")

==================================================
MRPC
train: 3668 samples
validation: 408 samples
test: 1725 samples
==================================================
QQP
train: 363846 samples
validation: 40430 samples
test: 390965 samples
==================================================
PAWS
train: 49401 samples
test: 8000 samples
validation: 8000 samples
==================================================
MSCOCO
train: 414010 samples

In [9]:
print("MRPC Example")
display(pd.DataFrame(mrpc["train"][:5]))

print("\nQQP Example")
display(pd.DataFrame(qqp["train"][:5]))

print("\nPAWS Example")
display(pd.DataFrame(paws["train"][:5]))

MRPC Example

,sentence1,sentence2,label,idx
0,"Amrozi accused his brother , whom he called "" ...","Referring to him as only "" the witness "" , Amr...",1,0
1,Yucaipa owned Dominick 's before selling the c...,Yucaipa bought Dominick 's in 1995 for $ 693 m...,0,1
2,They had published an advertisement on the Int...,"On June 10 , the ship 's owners had published ...",1,2
3,"Around 0335 GMT , Tab shares were up 19 cents ...","Tab shares jumped 20 cents , or 4.6 % , to set...",0,3
4,"The stock rose $ 2.11 , or about 11 percent , ...",PG & E Corp. shares jumped $ 1.63 or 8 percent...,1,4

QQP Example

,question1,question2,label,idx
0,How is the life of a math student? Could you d...,Which level of prepration is enough for the ex...,0,0
1,How do I control my horny emotions?,How do you control your horniness?,1,1
2,What causes stool color to change to yellow?,What can cause stool to come out as little balls?,0,2
3,What can one do after MBBS?,What do i do after my MBBS ?,1,3
4,Where can I find a power outlet for my laptop ...,"Would a second airport in Sydney, Australia be...",0,4

PAWS Example

,id,sentence1,sentence2,label
0,1,"In Paris , in October 1560 , he secretly met t...","In October 1560 , he secretly met with the Eng...",0
1,2,The NBA season of 1975 -- 76 was the 30th seas...,The 1975 -- 76 season of the National Basketba...,1
2,3,"There are also specific discussions , public p...","There are also public discussions , profile sp...",0
3,4,When comparable rates of flow can be maintaine...,The results are high when comparable flow rate...,1
4,5,It is the seat of Zerendi District in Akmola R...,It is the seat of the district of Zerendi in A...,1